### ISSUE TITLE
As an organizer I can edit details about the chapter, including a Slack/Discord/Facebook/WeChat/WhatsApp link participants can join to discuss and coordinate events.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#104]
The dashboard, /dashboard/chapters/[id]/edit will need a new Chat URL, so ChapterForm.tsx needs updating. 

The chapter details pages, /chapters/[id], should display the chat links.

**Comment by Ismailtlem** [comment]
Is this what's needed here ? 

![Screenshot from 2022-04-06 17-58-46](https://user-images.githubusercontent.com/34961373/162038692-4ab5f07a-ceda-4fc4-8085-8a98cbfb457a.png)

**Comment by ojeytonwilliams** [comment]
@allella I'm not 100% sold on this being MVP worthy, either.  It's clearly not a hard requirement, since we have email to communicate the important details. I'll remove the label.

@Ismailtlem if you're still interested in this (even if it's lower priority now!), then please go ahead.  

To your specific questions:

* Yes, an extra form field is what we need.
* Please just put the chat link wherever seems best to you.  

With UI design, it's always a little subjective, but feel free to experiment until you have something you like.
