### ISSUE TITLE
As a user / future participant after the event, I will automatically get emails notifying me of subsequent events.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#107]

**Comment by allella** [comment]
Below are preliminary suggestions and questions regarding this #107 and #276. The direction set forth here will also inform the text and email "mail merge" templates needed for #275 and #276.

**Assumptions / Suggestions**
- We're not going to introduce a 3rd party service dependency (e.g. MailChimp, Campaign Monitor) to manage subscriptions, opt-in and out, email templates, and alike. Rather, the application will send transaction emails using the #146 mailer defined in the `instance` mailer configuration.
- The [current schema](https://github.com/freeCodeCamp/chapter/blob/master/data/ddl.sql) doesn't offer a way to save a subscription preference.
- A single `instance` of the _Chapter_ application will usually have multiple `chapters` in the `organization` . The [terminology on the README](https://github.com/freeCodeCamp/chapter/#terminology) further explains the distinction between the _Chapter_ application / brand name and a `chapter` entity in the database.  So, when I say that someone 'Unsubscribes" from a `chapter` it doesn't necessarily mean they are turning off all notifications for a entire _Chapter_ application `instance`.
- We want the subscriptions to be specific to the `user` + `chapter`.  For example, if a `user` moves to a new city they may wish to stop notices from their former city's `chapter`, but still receive notifications for their new city's `chapter`.
- To offer flexibility we can add a `user_chapters.subscribed` boolean field to the [database schema](https://github.com/freeCodeCamp/chapter/blob/master/data/ddl.sql) to store a subscription preference for each `user` + `chapter` row.  This field will be added in a new PR, or even as part of #253.
- _Chapter_ application `instances` could easily exceed the free-tier sending limits of 3rd party transactional mailer #146 services, thus needing a paid account. For example, SendGrid allows 100 emails / day for free, but you have to pay to go over the limit.
- The [MVP](https://github.com/freeCodeCamp/chapter/labels/MVP) will not have a `user` profile page to manage subscriptions.  Rather, a `user` will need to subscribe or unsubscribe when they are RSVP'ing #278 or canceling an RSVP #278 for an `event`.
- Additionally, a `user` may click the "Unsubscribe" link in an `event` email notification (#275 #276) to unsubscribe from future notifications for the `chapter` that created the `event`.
- A `user` cannot unsubscribe from notification for a specific `event`.  When they unsubscribe they will not receive any future notifications for that `chapter`  unless / until they re-subscribe to the `chapter`'s notices on a future RSVP.
- We don't require a `user` to be logged in for the "Unsubscribe" link to work.
- Similar to how modern password reset links work, the "Unsubscribe" URLs could use a query string that is a unique, one-way hash (for security) that maps back to a specific `user_chapters.user_id` + `user_chapters.chapter_id`.  Not sure of the technical implementation so this will need more vetting.
- When the "Unsubscribe" link is clicked the resulting URL will set the `user_chapters.subscribed` boolean to false.
- In the RSVP UI for #278 and RSVP cancellation UI #277, we'll use a [Material UI form component like a "Subscribe" Switch](https://material-ui.com/components/switches/#switches-with-formcontrollabel) , to allow a `user` to simply toggle their preference.

**Questions**
- Are there any #147 transaction email services offering high sending limits and/or no limits for non-profits? @QuincyLarson what is freeCodeCamp's current solution for sending transaction email without it costing a lot of money?
- @ceciliaconsta3 are there any #65 accessibility tips for how the UI component is labeled or displayed? Like, if we have a label of "Subscribe", then does that work well with a screen reader, or do we need to phrase it in the form of a question?

**Comment by allella** [comment]
Also, I noticed after the fact that this comment may have been better on #274. However, since the RSVP, subscribe / unsubscribe, and email notices are all intertwined I'm not sure it matters much as long as it doesn't confuse this API issue.

**Comment by ceciliaconsta3** [comment]
@allella A label is definitely the surest bet.  If, and it sounds like, we will use the Subscribe component in a form alongside other elements to complete an ```event``` sign-up,  (if MVP won't have a User Account Settings page) we should treat the Subscribe switch as a checkbox using checkbox role instead. It'll get sent at form submission with the other fields. 

I think "Active" color as Subscribe/unchecked status and grey/disabled for Unsubscribe/checked status would do.

**Comment by ceciliaconsta3** [comment]
Let me know if I covered this logic flow correctly:

**1. _User is automatically subscribed to ```chapter``` notifications on joining_** (assuming user email address a required field)
- user must join a ```chapter``` in order to attend respective ```event```

**2. User subscription at ```event``` RSVP level:**
- user never subscribes using Subscribe switch > never gets ```event``` specific confirmation email (?)
- user does subscribe > unable to unsubscribe from ```event```specific notifications until they un-RSVP or the event date passes 

**3. User subscription at ```chapter``` level through ```event``` specific email:**
- user is able to unsubscribe from respective ```chapter``` notifications solely via email link in MVP
    - unsubscribe confirmation email should be sent and ```user_chapters.subscribed``` flag  updated
- user is auto-subscribed to ```chapter``` notifications upon joining next ```chapter event``` (?). 
- user still granularly controls whether they receive ```event``` specific email notifications.

(?) something to evaluate/discuss, perhaps after MVP ships

As for the user + chapter subscription relationship, autogenerate unique event keys based on userID + chapterID + eventID in new Subscription table?

**Comment by ceciliaconsta3** [comment]
Let me know if I covered this logic flow correctly:

**1. User is automatically subscribed to chapter notifications on joining** (assuming user email address a required field)
- user must join a chapter in order to attend the respective event

**2. User subscription at event RSVP level:**
- user never subscribes using Subscribe switch > never gets event specific confirmation email (?)
- user does subscribe > unable to unsubscribe from eventspecific notifications until they un-RSVP or the event date passes

**3. User subscription at chapter level through event specific email:**
- user is able to unsubscribe from respective chapter notifications solely via email link in MVP
    - unsubscribe confirmation email should be sent and user_chapters.subscribed flag updated
- user is auto-subscribed to chapter notifications upon joining next chapter event (?).
- user still granularly controls whether they receive event specific email notifications.

_(?) something to evaluate/discuss, perhaps after MVP ships_

As for the user + chapter subscription relationship, autogenerate unique event keys based on userID + chapterID + eventID in new Subscription table?

**Comment by allella** [comment]
Thanks, replaying the logic highlighted some potential areas of confusion with only having subscriptions toggle on / off via RSVP or unsubscribe link.

This user story suggested getting upcoming event notifications AFTER you've attended, but with Meetup.com I believe it's possible to subscribe and get notices without ever having attended.  That's a reasonable expectation too, though not explicitly an MVP story.

I guess we could also have a button on a `chapter` landing page to subscribe to all `chapter` email notifications whether they be reminders of upcoming events or reminders, general notifications (not an MVP that I've seen), or reminders about your RSVP (#108 & #276).

The question now is if subscribing and unsubscribe is connected to an RSVP and `event` (#108 & #276). Or, are subscriptions intended for upcoming events and more general announcements.

I could see a use case for both and we already have an MVP story for both cases.  If we do both then I suspect we'd need to add an `rsvp.subscribed` to the schema to allow for subscribing or unsubscribing from a specific event's notifications vs non-event notifications.

**Comment by allella** [comment]
To summarize, would the following be a reasonable MVP flow?

`rsvp.subscribed` would be added to the schema as a boolean to be toggled on or off by an authenticated `user` via the `chapter` landing page, like a "Follow / Unfollow" UI button or toggle.  This would turn on notifications which are not related to a `user` RSPV.

Such email notifications would have a URL to allow the `user` to "Unfollow {Name of Chapter} Notifications".

If we needed to trim the scope, then these emails could simply have a link going directly to the `chapter` landing page where the Follow / Unfollow button would need to be toggled. The downside here is the `user` would need to be logged in to stop receiving these notices.

`user_chapters.subscribed` would be added to the schema as a boolean and this field would be for notifications which are directly related to a specific `event` + `user` RSVP. 

The user would be able to click an "Stop Receiving Notifications for This Event" unsubscribe link.  If we narrowed the scope here as well, then the email could direct the user to the `event` landing page.  Again, this more simple approach would have the downside of requiring a `user` to be logged in and then toggle a button on the landing page to disable.

**Comment by madaleneaza-design** [comment]
@allella @ceciliaconsta3  I have been reading your comments in both this issue and #274  and already got some questions! But I will start off with one or two...

Not sure if the `user` will have a general account setting page or not, but for assumption's sake, let's say there is. There could be a page for managing subscriptions (via both notifications or emails) and for a` user` to find this page in one of these two ways, which is either:

- the `user` goes to the `chapter` page that they are part of and click on the subscription setting button
- the `user` goes to their general account setting page which has tabs of different types of settings and the subscription tab could be one of them.

So, once the `user` starts receiving emails (after going to the event) and they want to unsubscribe, they can click on the 'unsubscribe' link, which takes them to the managing subscription page. 

I hope my point is relevant to this issue. If so, what is your thought on this?

**Comment by allella** [comment]
@madaleneaza-design I think we've been operating on the assumption that a profile / subscription page not an MVP feature.  It's definitely a reasonable expectation to add one to the Roadmap, but so far there's been no explicit MVP user story a profile page to do anything since authentication will be using Google so we don't have an immediate need for _users_ to manage their email, password, profile picture, and such.

Would you agree we can start by allowing subscribing or unsubscribing to an _event_ or a _chapter_  using the MVP interfaces we know are already required?

If we didn't have a profile / manage your subscriptions page, for MVP, then we can still allow _users_ to subscribe and unsubscribe using links or buttons on these MVP interfaces.

- RVSP page (UI #278) using a checkbox to opt-in to an event's notifications via the RSVP form 
- the _event_ landing page  #270 (a UI for the user is implied)   via a "Follow this Chapter" switch
- the _chapter_ landing page #273 (a UI for the user is implied)  via a "Follow this Event" switch
- _event_ reminder emails #106  would have "Unfollow {chapters.name} Notifications"
- _chapter_ notification emails #276 would have a  "Stop Receiving Notifications for {events.name}"

@ceciliaconsta3 posted suggestions on [checkbox, vs switch vs buttons](https://github.com/freeCodeCamp/chapter/issues/274#issuecomment-562442271) for the UI on #274

**Comment by madaleneaza-design** [comment]
@allella Yeah I can agree and I cannot see why not (to allow subscribing and unsubscribing using the known MVP features), as long in terms of user experience,  the links/ UI elements are easier to navigate and use in the layout (which I am sure it will be). 

I will hop onto #274 to post my response :)

**Comment by allella** [comment]
For the more technical side of the mail sending, we had a good conversation in [today's meeting on using nodemailer and SMTP with free / cheap tiers of 3rd party transactional mailing services](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-23,-2020#email-service).

**Comment by allella** [comment]
@davidals brought up that we'd want a scheduled trigger to check for and send email notifications for event _rsvps_ and other such "X days before" notifications.  That's being discussed on #359.

I [referred the earlier suggested schema changes](https://github.com/freeCodeCamp/chapter/issues/107#issuecomment-562432174) to allow for unsubscribing from a specific _rsvps'_ notifications and a specific _chapter's_ notifications.

However, upon reviewing the talk about "Following" or "Unfollowing" a Chapter or RSVPs I found that "Following" an event may not make sense.  So, here's a refined view of toggling email notifications on or off.

**Toggling _[rsvps.subscribed](https://github.com/freeCodeCamp/chapter/blob/master/data/schema.png)_ on or off**
- (toggle on) _rsvp_ page (UI #278) using a checkbox to opt-in to an event's notifications via the RSVP form would set _rsvps.subscribed_ to TRUE or FALSE based on the form's input.
- (toggle off) the _event_ landing page  #270 (a UI for the user is implied)  via a "Unfollow this Event" switch if the _user_ has previously RSVP'ed through the RSVP form and _rsvps.subscribed_ is TRUE.
- (toggle off) _event_ reminder emails #275  would have "Stop Receiving Notifications for {events.name}" to set _rsvps.subscribed_ to FALSE

**Toggling _[user_chapters.subscribed](https://github.com/freeCodeCamp/chapter/blob/master/data/schema.png)_ on or off**
- (toggle on or off) the _chapter_ landing page #273 (a UI for the user is implied)  via a "Follow this Chapter" switch, or an "Unfollow this Chapter" if there is a _user_chapter_ record for the current _users and the user_chapters.subscribed is TRUE
- (toggle off) _chapter_ notification emails #276 would have a  "Unfollow {chapters.name} Notifications" to set _user_chapters.subscribed_ to FALSE

**Comment by davidals** [comment]
I think it's also valuable to have an account setting for that. 
Something like `notifications_allowed` that would override all of the `subscribed` when set (And default subsequent RSVPs to false), 
and when a user intentionally chooses to subscribe it would toggle the account level back to on.

**Comment by allella** [comment]
@ceciliaconsta3 @madaleneaza-design @davidals @Zeko369 

One other consideration is the following:

**Canceling an RSVP vs Unfollowing an Event**
Toggling off the "Follow this Event" switch on an _event_ page, for _users_ with an existing _rsvp_, would not necessarily mean cancelling the RSVP.

It's likely an _organizer_ wants to see who cancelled their RSVP, which means we'd need an _rsvp.canceled_ field to store that value instead of deleting records in the _rsvp_ table.  I don't think we need to implement the cancellation feature for MVP, but what are thoughts on updating the schema to cover this future use case?

The _event_ page would then have a "Cancel my RSVP" (button) to go along with the previously mentioned "Follow this Event" switch.  It seems like a fair assumption that cancelling an _rsvp_ would immediately sets the rsvp.canceled to TRUE and rsvp.subcribed to FALSE.

I was wondering if we should allow someone to follow an event without being subscribed to it, but I feel that could lead to confusion if someone clicks to follow and event and assumes that means they are RSVP'ed.  That could be a real problem if people show up to an event and don't have a ticket.  So, it's probably best we don't show both a "Follow this Event" switch unless the _user_ has active (not cancelled) _rsvp_ record.

Thoughts?

**Comment by davidals** [comment]
I think this is where language get's handy.

Instead of "follow" call it "Interested", and the toggle should say something like  "Notify me of updates to this event"

Agree on canceling RSVP makes you stop receiving notifications.

If you think about Facebook Events, there are 3 options "Not going, Interested, Going".
We could use a similar approach (and maybe even wording) since people should be familiar with the concept.

**Comment by allella** [comment]
Sounds good.

So the "RSVP" buttons could be "Going" and "Not Going", depending on if the _users_ already has an _rsvp_.

Then, a "Interested" UI slider to goggle on/off interest regardless of the _rsvp_ status.

**Comment by davidals** [comment]
Here's the PR adding those fields: https://github.com/freeCodeCamp/chapter/pull/374

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/chapter/pull/640 gives us something to work with, but it's far from a complete solution.

**Comment by Ravichandra-C** [comment]
> So the "RSVP" buttons could be "Going" and "Not Going", depending on if the _user_ already has an _rsvp_.
> Then, an "Interested" UI slider to toggle on/off interest regardless of the _rsvp_ status.

@allella @ojeytonwilliams Could you please let me know what work is remaining in this issue apart from the above UI changes?

**Comment by allella** [comment]
@Ravichandra-C 

When a [new _event_ is created](https://opensource.freecodecamp.org/chapter/tables/events.html) by an _organizer_ for a specific _chapter_, we will want to query the [_user_chapter_roles_ table_](https://opensource.freecodecamp.org/chapter/tables/user_chapter_roles.html) where _user_chapter_roles.chapter_id = _events.id_  (this will be the event id of the newly created event) AND _user_chapter_roles.interested_ = true.

There's a [basic example of the email to send to notify _users_ about new _events_](https://opensource.freecodecamp.org/chapter/tables/events.html). We'd want to merge in values from the _event_ and _chapter_ tables, as indicated by the { } placeholders in the example in that link.

We have a [separate issue to handle the unsubscribe links in the email footer](https://github.com/freeCodeCamp/chapter/issues/274). That issue may require more conversation and it could be somewhat complicated if we are trying to allow opt-out without being logged in.  So, for now, we can keep a placeholder where the unsubscribe links will go.

Does that help?

**Comment by Ravichandra-C** [comment]
>When a new event is created by an organizer for a specific chapter, we will want to query the user_chapter_roles table_ where >_user_chapter_roles.chapter_id = events.id (this will be the event id of the newly created event) AND >user_chapter_roles.interested >= true.

@allella , Currently we have the below functionality

When a new event is created by organizer in a specific chapter, We query user_chapter_roles table where user_chapter_roles.chapter_id=chapter.id( id of the chapter in which the event is created ) and user_chapter_roles.interested = true and send an email with below text.

![image](https://user-images.githubusercontent.com/17808008/135046416-2b24d7cc-4d12-4b96-98fb-bb79139c1ddd.png)

> _user_chapter_roles.chapter_id = events.id 

Shouldn't this be assigned with chapter.id instead of event.id?

>There's a basic example of the email to send to notify users about new events. We'd want to merge in values from the event >and chapter tables, as indicated by the { } placeholders in the example in that link.

the basic example hyperlink is liked to schema spy. Could you please provide the text that should be used in the email ?

PFB the template of the email that we are currently Sending when a new email is created(Code is already in the repo).

   ```
 const subject = `Invitation to ${event.name}.`;
const body =
      `When: ${event.start_at} to ${event.ends_at}<br>` +
      (event.venue ? `Where: ${event.venue?.name}<br>` : '') +
      `Event Details: <a href="${eventURL}">${eventURL}</a><br>
<br>
- Cancel your RSVP: <a href="${eventURL}">${eventURL}</a><br>
- More about ${event.chapter.name} or to unfollow this chapter: <a href="${chapterURL}">${chapterURL}</a><br>
<br>
----------------------------<br>
You received this email because you follow this chapter.<br>
<br>
See the options above to change your notifications.`;
```

> for now, we can keep a placeholder where the unsubscribe links will go.

Sure, I'll add the place holder for unsubscribe link.

**Comment by ojeytonwilliams** [comment]
@allella @Ravichandra-C I think this is largely done - we are automatically sending the notification emails already.  If someone has _user_chapter_roles.interested_ they will be emailed whenever a new event is created on that _chapter_.  However we still need to

- set _user_chapter_roles.interested_ to be true when they RSVP to an event for a chapter
- add the unsubscribe placeholder

We should only set _interested_ to be true if the user doesn't yet have a _user_chapter_role_ for that _chapter_.

I think that's all we need for now.

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams ,In addition to the above changes ,Should I also include these UI changes as part of this issue?

>So the "RSVP" buttons could be "Going" and "Not Going", depending on if the user already has an rsvp.
>Then, an "Interested" UI slider to toggle on/off interest regardless of the rsvp status.

**Comment by ojeytonwilliams** [comment]
@Ravichandra-C I'll handle that in a separate PR :)

**Comment by allella** [comment]
@Ravichandra-C I probably had an error above in the logic.  I trust you understand what needs to be done on the technical side, so we should be good to proceed with what you have.

Thanks

**Comment by Ravichandra-C** [comment]
@allella @ojeytonwilliams Thank you for explaining. I understood what needs to be done. I'll be working on it.

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams , For setting the user_chapter_role.interested=true when an user rsvp to an event, I'm creating a new mutation with name _SetUserInterestForChapter_ which takes the event_id as the parameter. Could you please let me know if we already have this mutation? I just wanted to make sure that I'm not adding duplicate code.

**Comment by allella** [comment]
It makes sense that most _users_ will be happy to get notified of future events for a _chapter_, but what if a _user_ had previously toggled _user_chapter_role.interested_=false?

It sounds like this user story would set _user_chapter_role.interested_=true without asking, but a _user_ may not want to get  future notifications.

Would we want to show a toggle field on the RSVP form, set that toggle's default value to match the _user's_ current value for _user_chapter_role.interested_, but still allow them to toggle / change it when they RSVP?

There are events in my town that I might only attend once a year, or for a special occasion, but that doesn't mean I necessarily want to be forced to receive future notifications. 

Thoughts?

**Comment by Ravichandra-C** [comment]
@allella , This mutation will check if user already has a preference set in the database, if it is already set, then we are not doing anything.If it is not set then we are by default setting the user_chapter_role.interested to true.

**Comment by ojeytonwilliams** [comment]
> It sounds like this user story would set user_chapter_role.interested=true without asking, but a user may not want to get future notifications.

We definitely don't want to do that and Ravi's proposed logic should work as intended.

> Would we want to show a toggle field on the RSVP form, set that toggle's default value to match the user's current value for user_chapter_role.interested, but still allow them to toggle / change it when they RSVP?

Seems reasonable, yeah.  We could have it default to true when _user_chapter_role.interested_ is not set and just mirror their settings once _interested_ has a value.

>  I'm creating a new mutation with name SetUserInterestForChapter which takes the event_id as the parameter. Could you please let me know if we already have this mutation?

We don't have any mutations that change _user_chapter_role.interested_, so please go ahead.

> I searched in the repo and also the generated/graphql.tsx but I did not find it, I just wanted to make sure that I'm not adding duplicate code.

Cool. Just to aid any future searches: all mutations must be defined in either a `queries.ts` or a `mutations.ts` file (ideally the latter!), so if they're not in a file with those names they effectively don't exist.
