### ISSUE TITLE
As a user / future participant I can click the "RSVP" button, I will receive an email with a confirmation, and I'll be added to the public list of event attendees.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#110]

**Comment by xarielx** [comment]
Since we are adding Chapter to existing Organizations, one concern is integrating the existing users of that page into Chapter, or for the MVP are we're going to stick to create new users independent from the Orgs? @allella @chrismgonzalez

**Comment by allella** [comment]
@xarielx If I'm understanding you correctly, are you asking if an organization has existing users from another platform then are we going to allow importing users to the organization and/or specific chapters within the organization? 

We may be able to start with only authorization and logging in for organizers and admins, since we can probably validate a user's email address and RSVP them through email validation links. 

The user and auth discussion, even for the MVP, is way beyond just me and Chris so we'll need to tickle the folks on #40 who have been thinking even further beyond the MVP.

**Comment by xarielx** [comment]
Ok did not see that issue I apologize, but my concern is: if the organization has their own logging system, let's say Rotary International, you sign in to their site, if you go to their Chapter.rotary.org, would need to log in with different credentials? Or is their tools to Integrate them. I don't know if that clarifies it, but ill mention it in #40

**Comment by allella** [comment]
@xarielx I think #40 was focused on shared logins between Chapter organization servers/instances.  I don't foresee much in the way of universal logins that integrate with a specific organization's proprietary auth systems.

Single Sign On (SSO) using popular services like Google, Facebook, have been mentioned, like in #90 and it sounds like they are on the post-MVP roadmap.

Again, I'll defer to the folks in #40 #90 and any other auth threads on the best place to start with Auth for the MVP that doesn't paint Chapter into a corner.

**Comment by vkWeb** [comment]
@xarielx You are making a very valid and correct point. Actually what my thoughts for MVP is that we should not have a universal login. 

For e.g. freeCodeCamp.org and freeCodeCamp.org/forum which is built on top of discourse need different accounts.

**Comment by QuincyLarson** [comment]
@vkWeb Yes - this is what I'm thinking. Chapter would have its own authentication, and if necessary the organization could figure out a way to unify Chapter accounts with their own accounts. In many cases, Chapter would be the only part of a nonprofit's website that would even have accounts, as many nonprofits just have mailing lists of participants and donors. In these situations, the organization wouldn't need to bother with any further authentication work.

**Comment by bernhard-hofmann** [comment]
Is this the right place to mention that the RSVP wait list isn't a queue? The schema indicates whether a user is on the waiting list as follows:

`on_waitlist boolean not null default FALSE`

If we want to give the first available places to the people who applied first, we could use a queue position system where position > event capacity means the user is on the waiting list.

`queue_position int not null default 1`

**Comment by allella** [comment]
Related: [Authentication notes from the Nov 15th meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-November-15,-2019#authentication).

**Comment by AryanJ-NYC** [comment]
IMHO, this ticket is a prime candidate to be broken into pieces. Some ideas of tickets that can come of this one:

1. As an unauthenticated user, when I click the RSVP button, I will be prompted to sign in. On sign in, 2 and 3 will follow. Blocked by 2 and 3.
2. As an authenticated user, when I click the RSVP button, I will be added to the public list of event attendees.
3. As an authenticated user, when I click the RSVP button, I will receive an email with a ticket.

**Comment by allella** [comment]
@AryanJ-NYC 
I could see splitting the authentication, your number 1 above, into a new API user story issue.

Also, we have a ["Log In" link in the Figma mockup navigation](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down).  The logic for logging in would be a subset of the logic required to authenticate and RSVP, so perhaps we also need API and UI stories for "Log In".

We'd need to rename this issue and #278 to be specific to adding a _user_ to _rsvps_ list and send an email, since those would constitute actions inside of a single transaction.

**Comment by allella** [comment]
Also, in thinking through documentation for user account and notifications (https://github.com/freeCodeCamp/chapter/issues/262) it's not immediately clear how a "Register" page / step would work with our [Google authentication constraint](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-November-15,-2019#authentication).

If you're a new _user_ and you've never logged in, then does the Log In page simply direct the _user_ to Google and then the user log in or register steps are handled by Google?  If that's the case then do we even need a "Register" page for the MVP, since Google would handle any registration?

Even after a _user_ registers and / or signs in with Google, then it seems we may want to collect basic account information upon first log in, or first RSVP.

Questions, assuming we need basic _user_  account information:

- What's are the MVP minimum _user_ fields that we need to collect?
- When do we collect these fields? At first log in, or first RSVP?
- The schema has _user_ first name and last name.  Would we plan to pull first name and last name from the Google profile, if that's even allowed? Then, pre-populare a first name and last name with Google's values, but still allow the user to change their name values? 
- Privacy preference: there's no user story, yet, but Quincy also suggested on #262 to have the ability to mark a profile as private.
- In addition to making a profile private, do we offer to make an RSVP private? For instance, only the organizer and admin would see the person's info on a reservation list and the reservation list would show something like "Private Guest".
- Do we consider any other fields as part of a basic profile? I could see an avatar image being visually useful if we could pull it from Google's profile, but I'm not convinced it's an MVP need.  Allowing users to upload a profile image / avatar could introduce a need for 3rd party CDNs, so that's a can of worms we likely don't want to open for MVP.

**Comment by madaleneaza-design** [comment]
@allella I am glad you have mentioned this. If we are only using Google authentication, then the registration page and sign in page is not actually making sense as it has "register with email" form and "login with email" link. Plus, I am not sure if it is relevant to have two separate pages (registration and sign in) since the link "Continue with Google" actually redirect you to the same pop-up box asking the user to choose one of their Google accounts. That is unless I am missing something and something does happen after you either sign in or register (for example, once a user registered, it will take them straight to their profile page so they can add bio details etc).  

It is clear that on the UI side, we need to re-create this. But, In this case (or issue), if the user is not signed in or have never registered with the chapter before, and they clicked the "RSVP" button, a pop up modal with one link could appear indicating the user sign in OR register. Once the user clicked it, it will redirect them to the page where the user chooses one of their Google accounts before taking the user to whatever is required in the next step.

What is your thought on this?

**Comment by AryanJ-NYC** [comment]
Just a quick sanity check:

I remember @QuincyLarson mentioning offline use (using the prison system as an example). I imagine "only using Google authentication" would not work in this situation...

**Comment by allella** [comment]
@AryanJ-NYC Quincy's comment on offline use was in the context of a developer viewing Swagger API documentation on their localhost vs on a hosted platform.

I think the line of reasoning was that someone in the prison system, or just someone with limited internet access (traveling, flying, camping), may benefit with having dev documentation, like Swagger, available on their localhost.

So, I don't think we have to worry about the site running offline.

**Comment by AryanJ-NYC** [comment]
Ah, OK. Cool. Just wanted to make sure.

**Comment by allella** [comment]
@madaleneaza-design I'm thinking we take @AryanJ-NYC suggestion and split off an authentication specific UI and API issue.  Then, leave this issue to be about _RSVP_ and sending the _user_ a confirmation email.

It's still going to be the case that the user needs to be logged in, via Google, to RSVP but I suspect authentication (login and register) doesn't need to be entirely tied up in this issue.

**Comment by madaleneaza-design** [comment]
> @madaleneaza-design I'm thinking we take @AryanJ-NYC suggestion and split off an authentication specific UI and API issue. 

@allella I am with you on this one. The more we break all the user stories into smaller pieces, the clearer it is to know what can be (appropriately) discussed and what is needed to be created.

**Comment by Zeko369** [comment]
Done in #636
