### ISSUE TITLE
Ability to filter event/events

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1211]
### Discuss your ideas or share your views: 
Make sure to tell how your idea will benefit this project.

I want to create the ability to filter our data with input from the users, I am started with event/events because it seems the easiest.

Here is the prototype of how it looks.

![image](https://user-images.githubusercontent.com/88248797/178519726-5faa1df3-a1d9-4754-b84e-0a5920df1493.png)

While creating the interactivity, I realized there are multiple ways to go about this. 

So first, Is this something that is needed?

if yes

- is the filter option remembered after the session ended?
- Does the filter option hide the data or change how the data being request?
- I am sure you guys have more questions or inputs that will polish this function

**Comment by allella** [comment]
There is a filter option on the events page in an [early mockup](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=332%3A355&scaling=scale-down), but I don't believe we've had an issue for the filtering, [MVP](https://github.com/freeCodeCamp/chapter/issues?page=2&q=label%3AMVP) or otherwise. 

There is a conversation about [adding an event search bar](https://github.com/freeCodeCamp/chapter/issues/349), but that's also been put on the [Roadmap](https://github.com/freeCodeCamp/chapter/issues?q=is%3Aissue+label%3ARoadmap+is%3Aclosed) and I'd suggested that [location filter is probably the most important filter](https://github.com/freeCodeCamp/chapter/issues/444#issuecomment-792865668) and that may still be the case since freeCodeCamp is likely to host an instance for beta testing with events in various cities.

I feel like the search feature is still not and MVP issue.  Though, there may be a case for 1 or two filters, like the location, but the  fCC staff like @ojeytonwilliams and @nhcarrigan may have a better feel for the scope of the fCC testing and if filters are needed for MVP.

One other note is that [we've talked a bit about UI elements, like switches vs checkboxes](https://github.com/freeCodeCamp/chapter/issues/274#issuecomment-562442271), and Cecilia linked to this [switch vs checkbox comparison](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8).  This in the context of Accessibility as well, which we may want to have someone look, like @ceciliaconsta3 , around and pick out any major accessibility issues before the MVP goes live.

**Comment by Sboonny** [comment]
> but I don't believe we've had an issue for the filtering, MVP or otherwise.

True, I am trying to create a function similar to what [Quincy mentioned in his comment in issue 274](https://github.com/freeCodeCamp/chapter/issues/274#issuecomment-565726460), without holding the issue hostage like how I did in issue #276 , stopping people who see my pull request from opening pr and not fixing the issue instead.

And I think filtering the events depending on user interested in it, will create similar function. Although I may be wrong and I am wasting time.😅

> There is a filter option on the events page in an [early mockup](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=332%3A355&scaling=scale-down),

Thank you🤍, I will use it moving forward.

About the UI and SEO concerns, I will be honest. I was lazy because that wasn't my original goal, but after reading your comment, I will give them extra care 👍

**Comment by Sboonny** [comment]
closed in favor of #2188
