### ISSUE TITLE
after edit some event details and press "save" - better to add notification about operation status

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/chapter#1274]
### Discuss your ideas or share your views: 
after edit some event details and press "save" better to add notification about operation status - if the changes saved successfully or some error occurred

**Comment by Awais753** [comment]
Can i work on this?

**Comment by gikf** [comment]
> Can i work on this?

Sure, no need to ask. Let us know if you'd have any questions.

**Comment by Awais753** [comment]
I tried to edit an Event's capacity field just for experimenting and I get this error in response.

> return await prisma_1.prisma.events.update(
  Null constraint violation on the fields: (`chapter_id`)
  
 Is this a known issue? or is it from my end only.

**Comment by gikf** [comment]
It's definitely not normal. Could you try reseting/seeding database and try it again? `npm run db:reset` or `npm run db:seed`. If you will be able to reproduce it again, please create an issue.

**Comment by Awais753** [comment]
running `npm run db:reset` fixed the issue. 

Actually I am not using docker because it continuously caused issues with `chapter-app`  container. The container runs command `sh -c './wait-for db:5432 -- npm run dev'` on start and exited with message that `./wait-for not found`. So I decided to setup without docker. I ran npm scripts manually in order:

1. `npm run db:sync`
2. `npm run db:seed`
3. `npm run dev:server`
4. `npm run dev:client`

I still don't see why this would have caused any issue here.
