### ISSUE TITLE
Improvement: Sequelize behaviour

### ISSUE THREAD

**Issue by vaibhavsingh97** [freeCodeCamp/chapter#160]
After https://github.com/freeCodeCamp/chapter/pull/120 merge, we have sequelize in place, and now we can create models and other things. There was one concern raised by @timmyichen as follows:

> initSequelize() generate the sequelize instance vs having it be created and exported as part of the db.ts file since it's synchronous? We'd need to access the sequelize instance in other places e.g. when we want to do transactions.

This issue is open for discussion and available for first time contributors to fix it.

**Comment by papigers** [comment]
Not sure I understand, you want to separate the sequelize instance initialization and its' export?

**Comment by timmyichen** [comment]
> Not sure I understand, you want to separate the sequelize instance initialization and its' export?

We should initialize a single sequelize instance in the lib, export that, and reuse it everywhere we go

**Comment by papigers** [comment]
That's not what we're already doing? `initSequelize` **is** the sequelize instance, right? It's not a factory function like hinted in the quote from the PR.

**Comment by timmyichen** [comment]
Ah looks like we completely overlooked this part of a commit:

https://github.com/freeCodeCamp/chapter/pull/120/commits/323e6d8cd1784c0e2d93b0e23db930794b2cae9a#diff-750f3d5cd257576112b47e8d33e0428cR3

This issue can be closed since this was already addressed in #120.  Maybe a small thing would be to rename it from `initSequelize` to just `db` or something

**Comment by Zeko369** [comment]
I can rename it in the seeders PR
