### ISSUE TITLE
Header inconsistent height for logged/not logged users

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1653]
There's slight difference in the height of header, depending if user is logged in or not. It'd be good to have it the same for both states.

![image](https://user-images.githubusercontent.com/60067306/193652164-d5420452-88d0-4140-a9fc-ba27f710cff7.png)![image](https://user-images.githubusercontent.com/60067306/193652174-31e32766-b1b7-448f-a21d-c337c05e8831.png)

**Comment by Sboonny** [comment]
This issue happen because when user is logged in, the `Avatar` component is mounted which add height to the `navbar`.

freeCodeCamp has its header's `height` set to `36px` we can do the same. If the final outcome looks weird, we can use `4.5 em` this will give it more than enough space.

**Comment by DevWig** [comment]
Please assign me this issue. @gikf @Sboonny

**Comment by Sboonny** [comment]
@DevWig, there is no need for assignment. Feel free to open PR directly, after reading our contribution guide

**Comment by jaitjacob** [comment]
It looked like the Avatar component was adding an additional 10px to the Header height. My fix simply adds a fixed height & width to the Avatar component to match the Header Height. The width part is necessary so that the Avatar doesn't look chopped on top and bottom.

> "freeCodeCamp has its navbar's `height` set to `36px` we can do the same."

@Sboonny I couldn't find the height set to '36px' anywhere in the code. I checked the `Header.module.css` file. The height set by me is 50px and it looks visually correct.
