### ISSUE TITLE
Organize the team

### ISSUE THREAD

**Issue by jaburcodes** [freeCodeCamp/chapter#169]
### Discuss your ideas or share your views: 
This project is running ridiculously slow IMO. Thats because it's missing some basic organization.

What i suggest is to create
- Core team of 3 engineers/developers and 1 PO.
- Having sprints.
- Having weekly/monthly review or planning calls.

If the development keep like it, the project will take 20x the time it should.

**Comment by Zeko369** [comment]
I suggest we talk about this on the team meeting this Friday. We could add it to the agenda @QuincyLarson?

**Comment by vkWeb** [comment]
@Zeko369 I agree with you.

**Comment by martineizayaga** [comment]
@Zeko369 What are the details about the team meeting?

**Comment by jaburcodes** [comment]
Creating a more organized environment will also avoid this lack of interest over time.
This project needs long term mantainers to grow:

<img width="758" alt="Screen Shot 2019-11-14 at 08 10 40" src="https://user-images.githubusercontent.com/13947203/68852309-6403b300-06b6-11ea-83a7-c2f318f6a2bb.png">

**Comment by Zeko369** [comment]
@martineizayaga If you haven't join the meeting this Friday, you can ask Quincy to add you to the gcal event.

**Comment by allella** [comment]
I'm still here and plan to stick with the project doing what I've been doing, which is mostly helping answer questions for newcomers and connect people when there are questions about the current status of things.

I'll be on the meeting tomorrow.

I'm a LAMP dev and don't have the experience, or desire, to make code contributions at this stage of the core tools and patterns being assembled.

A lot of what was pushed in originally was documentation and high level stuff that was easier for anybody to merge or understand.

I'll endeavor to ask more questions, but I'll agree that consistent contributors, technical and otherwise, will be necessary.  Though, I'm interested to see how that works with volunteers as I'm usually the only consistent one on the other projects where I'm the lead.

**Comment by QuincyLarson** [comment]
We will consider creating a core team later. For now, I think we have sufficient momentum.

I agree with @timmyichen that we need more clarity - not more hierarchy.

**Comment by timmyichen** [comment]
Just to add on because this was discussed during the meeting but not penned here:

By clarity, I think having the following would help facilitate PRs:
* More issues clearly labeled as Todos (clientside work should include mocks/etc)
* Close stale PRs e.g. older than 7 days
