### ISSUE TITLE
Home Page Query is a trap that can catch dev off guard when updating chapter Card or Event Card

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1724]
I have been trying to update chapterCard multiple times, and home page always gets in the way. I think because it doesn't follow our convocation by keeping the style in different component and the logic in others.

What do you guys think of refactoring it, so it looks similar to the header in #1669

Multiple components but one logic that rules them? 🤔

**Comment by ojeytonwilliams** [comment]
> So I want one page that send both logic to these components. If the logic in one page, the editor can warn me.

By logic, you mean data, right? I don't think that's possible.  Each page is responsible for fetching the data it needs and each page is one file.

So, essentially the problem is that changing components does not create an obvious warning in the editor.  It only shows a problem if you're looking at the pages that use the components.

This will always be caught when we run `tsc`, but I've been reluctant to run that as part of `lint-staged` because it slows down every single commit.

Since it will always get run before Cypress tries to do its thing, why not check there?

**Comment by Sboonny** [comment]
With the removal of home query, this issue is solved https://github.com/freeCodeCamp/chapter/pull/2340.

Note to self: how can't I communicate the need of home query deletion. 🤦
