### ISSUE TITLE
Parsing of date entered directly to Start at or End at inputs

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1781]
### Describe the bug:
`client/src/modules/dashboard/Events/components/EventForm.tsx`

When date is entered directly into the input field (ie. like it's done with cypress), the `DatePicker` tries to parse entered date from the first character. As `ends_at` and `start_at` fields are sometimes updated simultaneously - to not allow `start_at` to be after `ends_at`

To reproduce:
- Go to `/dashboard/events/new`
- Change _Start at_ date via input or `DatePicker` ie. to 15th of May 2022.
- Focus on the _End at_ input and start typing `2022-05-16 10:11`.
- After the first entered character (2), `DatePicker` will jump to February, and also _Start at_ date will be adjusted to not start after that date.

One option is using `strictParsing` in `DatePicker`. That prop will make parsing adhere strictly to the `dateFormat` prop, currently that's `MMMM d, yyyy h:mm aa`. Only after entering the full `May 16, 2022 10:11 AM` date would be parsed by `DatePicker`, so the _Start at_ date wouldn't be changed before that to some bogus date.

**Comment by ojeytonwilliams** [comment]
This sounds like something we want to handle with validation, rather than automatically updating the dates.  Reason being, it can easily be frustrating when unexpected changes (even helpful ones) happen without the user asking for them.  Especially when those changes are subtle (it's easy to miss that the start date has changed)

If we just warn users when the two dates are incompatible, that should be fine.
