### ISSUE TITLE
Server can attempt to create an existing user

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1984]
```
PrismaClientKnownRequestError: 
Invalid `prisma.users.create()` invocation:


Unique constraint failed on the fields: (`email`)
    at RequestHandler.handleRequestError (/usr/chapter/node_modules/@prisma/client/runtime/index.js:34310:13)
    at RequestHandler.request (/usr/chapter/node_modules/@prisma/client/runtime/index.js:34293:12)
    at async PrismaClient._request (/usr/chapter/node_modules/@prisma/client/runtime/index.js:35273:16)
    at async /usr/chapter/server/src/app.js:91:95 {
  code: 'P2002',
  clientVersion: '4.6.1',
  meta: { target: [ 'email' ] }
}
```

I'm not sure how this happens, because the `createUser(email)` call is immediately after a `findUser(email)` check, but I think it must be two simultaneous login attempts.

TODO:

- [ ] Investigate how/why/if that is happening
- [ ] `upsert` the user record instead (it's at least more idiomatic)

There's a nice discussion https://github.com/prisma/prisma/discussions/5815#discussioncomment-404334 about how to use `upsert` as a `findOrCreate` call and how to handle race conditions.

**Comment by atosh502** [comment]
Hi @ojeytonwilliams,

> Investigate how/why/if that is happening

This occurs when more than one API call (with the same `email`) concurrently calls `/login` endpoint. I don't know how to reproduce this in an end-to-end way (with both frontend and backend). But I was able to reproduce it by making multiple calls to `/login` endpoint at once using Apache Jmeter.

> `upsert` the user record instead (it's at least more idiomatic)

Prisma offers [two ways](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#remarks-8) to avoid the race condition while using `upsert`.

* The easiest of which uses database upserts to run the `upsert` query. Since our `createUser` query [modifies two models at once](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#database-upsert-query-criteria)(`users` and `instance_roles`), this method was not useful to us.
* The second method suggested catching the `unique key constraint error` and retrying the createUser operation. I used the second method to retry the `upsert` operation. Verified that this change resolves the issue.

**Comment by ojeytonwilliams** [comment]
Thanks for digging into this @atosh502. Your analysis makes perfect sense to me and I'm glad you were able to reproduce the error reliably.

It's interesting that Prisma can't handle the two model case, but simply catching the error should be a fine solution in case the client starts firing off multiple login requests again!  Hopefully that won't happen, but it's good that we can handle it.
