### ISSUE TITLE
Uncaught error when Auth0 login form timeouts

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/chapter#1997]
To reproduce, with Auth0 login:
- Click Menu and Login to display login form
- Wait around 60s
- `Uncaught (in promise) Error: Login required`

**Comment by Jonathan1599** [comment]
It looks like after a certain time period, [loginWithPopup](https://github.com/freeCodeCamp/chapter/blob/main/client/src/hooks/useAuth.ts#L11) fails and createSession is called which uses `getAccessTokenSilently` ( my prime suspect causing this bug). I think this is the case because the error disappeared when I commented createSession out.

I've implemented what I think is a temporary fix for now. Will try to find a better solution in the meanwhile.
