### ISSUE TITLE
npm install/audit found security flaws

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#259]
### Describe the bug:
Latest commit 0ed0d16
`$ npm install ` indicated some vulnerabilities

![vulnerabilities](https://user-images.githubusercontent.com/9598008/69659707-9c4eae00-1033-11ea-99fb-ac900a6bdd3f.PNG)

`$ npm audit --json` lists the details in the file attached to this issue
[npm-audit-26Nov2019.txt](https://github.com/freeCodeCamp/chapter/files/3893314/npm-audit-26Nov2019.txt)

### Tell us about your browser and operating system:
- Browser(s) name and version:  __Terminal__
- Operating System: `uname -or` __4.19.5-300.fc29.x86_64 GNU/Linux__

**Comment by bernhard-hofmann** [comment]
Could you copy and paste the output text from `npm audit` so that we have a record of the details?

**Comment by NorthDecoder** [comment]
See the link labeled `npm-audit-26Nov2019.txt` in the original comment?  Click on that link to get the output in text format.

**Comment by allella** [comment]
I believe it was [decided at today's meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-December-15,-2019) to use a different npm Swagger package since the security issues are not being address quickly by the current package's maintainer.

@nik-john @Zeko369 @vaibhavsingh97 is this correct? If so, can we close this and then do we need to create an issue to swap out to Swagger?

**Comment by allella** [comment]
Also, since we're changing from speccy then I suspect the [README on API Specs](https://github.com/freeCodeCamp/chapter#api-specification) will need to be updated.

**Comment by Zeko369** [comment]
Event though this hasn't been solved, I'll close this and open a new Issue to switch to SwaggerUI.
Also other vulnerabilities have been fixed
