### ISSUE TITLE
UI: As an organizer I can email the entire list of participants.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#267]
Depends on #99

**Comment by allella** [comment]
A couple features were noted in [Ayotomide's workflow's today](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-9,-2020#design-review) that I wanted to ask if we have an MVP issues, or else need if these are still post-MVP.

The ability to send message to users and invite them was, wisely, part of the flow.  Certainly these are useful features, but I'm not sure we have user stories for them.  Also, you can imagine organizers would need to reach out to their existing members through their existing platform (Meetup.com, Facebook) because they can't get their email addresses out of these systems anyway.

So, do we see a need for either direct messaging or inviting as an MVP feature?

This issue seems to focus on bulk messaging and not individual messages or inviting new users.

I personally think the organizers won't have people's emails until after they register for Chapter, so allowing them to message, invite, or import emails could all be putting the cart before the horse

**Comment by allella** [comment]
@tomiide

**Comment by allella** [comment]
@tomiiide
