### ISSUE TITLE
UI: As an organizer I can cancel events and all participants who have RSVP'd will get an email notification.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#268]
Depends on #100

**Comment by allella** [comment]
@Ravichandra-C I'm not sure why this issue was closed, but we can reopen it.

This will address cancelling an event and notifying the _members_  with an active _rsvp_ about the cancellation.

Here is the current UI, which doesn't have a field or button to initiate cancelling an event.

![image](https://user-images.githubusercontent.com/1777776/132703778-0db74602-6a6e-4352-9fad-f98aceae0696.png)

**Comment by gikf** [comment]
There's button for cancelling event on the `dashboard/events/x` page, should it be added here as well?

**Comment by allella** [comment]
@gikf adding a cancel button to the edit page sounds reasonable to me.

**Comment by allella** [comment]
Though, it sound probably be named "Cancel this Event" to avoid confusion with a "Cancel" button that's common to "exit" and cancel making changes to a form.

**Comment by ojeytonwilliams** [comment]
Once that button exists, I think we can close this.
