### ISSUE TITLE
Auth: As an owner or chapter admin I can create events and set their venue type, venue, video url, tags and capacity.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#270]
Depends on https://github.com/freeCodeCamp/chapter/pull/814

The UI is looking solid, so the main outstanding issue is to add auth and test it, similarly to 
https://github.com/freeCodeCamp/chapter/issues/273

- [x] As an owner I can create events in any Chapter
- [x] As an admin of Chapters, I can create events in those Chapters (but no others)
- [x] As any other role, I cannot create events

The main thing to check is that requests from unauthorised users fail, but it's also helpful to confirm that the UI reflects their role.

**Comment by Zeko369** [comment]
Hey @madaleneaza-design how is the design for this coming along? I was thinking about building the api for this tomorrow, and also doing a skeleton in react for this, so if you already have something I'd like to implement that

**Comment by allella** [comment]
Venue Type is an addition field discussed in 
https://github.com/freeCodeCamp/chapter/issues/378
and 
https://github.com/freeCodeCamp/chapter/issues/382

**Comment by allella** [comment]
@katien 

https://github.com/freeCodeCamp/chapter/issues/270 is a relevant user story for the UI side.

We don't have a more granular issue for implementing specific form fields to show/hide other location or video URL field based on the type of event, so for now this issue / user story could cover the form fields on the event creation page.

**Comment by allella** [comment]
The idea on the [event's venue type UI element](https://github.com/freeCodeCamp/chapter/issues/378) would be to only display the relevant form fields.

- if Venue Type = Physical, then show address fields
- if Venue Type = Online, then show video URL field

**Comment by allella** [comment]
@katien I'm coping the authorization notes for CRUD an event here since they are relevant to this user story.

(via Discord) I don't think we have the permissions logic entirely figured out yet, but the ability for a *user* to post *events* on 1 or more *chapters* will depend on their authorization. 

Authorization will come from either of
- **user_chapter_roles** with possible role values **_organizer_**, _**member**_. A _user_ can have 0 or more roles per _chapter_.
- **user_instance_roles** with possible role values _**owner**_, _**administrator**_

Lots of earlier discussion on this issue led to this summary https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-585347150 which was then closed via PR: https://github.com/freeCodeCamp/chapter/pull/335

 A *user* with the role of *owner* or *administrator* would be able to CRUD *events* for all *chapters* in the *instance* and we infer that from their role in **user_instance_roles**  and any *event.chapter_id* values would be from a drop-down field that populated with all values from the **chapters** table.

An *organizer* would be a *user* with specific authorization role entries via the **user_chapter_roles** table.  They would have 1 or more such roles previously granted by the *administrator* or *owner*.   The **user_instance_roles.chapter_id** values would be joined to the *chapters* table to populate a form field (drop-down) of possible values for **events.chapter_id** when an *organizer* creates or updates an _event_.  Or, in the case the *organizer* only has authorization to a single *chapter*, then perhaps the app logic forces the **events.chapter_id** to that specific **chapter_id**

The role tables aren't reflected in the out-of-date schema ER diagram, but the rest of the earlier schema is shown at
https://github.com/freeCodeCamp/chapter/blob/master/docs/data/schema.png

https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-723372850

**Comment by allella** [comment]
I've changed the title to include owner and admin, since they will have the same abilities.

**Comment by Ryuno-Ki** [comment]
Pressing <kbd>y</kbd> for the schema image led me to https://github.com/freeCodeCamp/chapter/blob/4d271782e56228b567e7d0290b243cf084ffffb0/docs/data/schema.png (a permalink)

**Comment by allella** [comment]
@Ryuno-Ki I'm not sure what the last comment was suggesting. Is that a good thing or a problem?

**Comment by Ryuno-Ki** [comment]
Imagine, the file gets moved to another place. Or updated. The image you referenced to wouldn't be the image you had in mind (but the recent one - if at all), because you're pointing to `master`. I'm pointing to the same image at the point of commit, i.e. a fixed point in time.

In case you want to learn how I get there, I left the hint (pressing <kbd>y</kbd> on your keyboard. More shortcuts at <kbd>?</kbd>), since I realised, that these are often unknown to GitHub users.

**Comment by allella** [comment]
A fair point. For this issue, it was more of a side note that the schema needs work like we have open in #54.  We have needed to pay attention to that issue in the docs, so I'll do better to keep it in mind on comments depending on if it matters in the context.  THanks

**Comment by allella** [comment]
Recent [conversations](https://github.com/freeCodeCamp/chapter/pull/735#issuecomment-944167783) lead to a more firm "line in the sand" on the use of the "role" tables and the [definition of the term "role"](https://github.com/freeCodeCamp/chapter/pull/744).

Also, we now expect to have _user_instance_roles_, _user_chapter_roles_, and _user_event_roles_, which adds to the earlier conversation in this issue about these "_role_" tables.

Conversely, non-role / non-authorization based fields will exist in tables like _user_chapter_details_, _user_event_details_, and perhaps even _user_instance_details_.

This conversation is relevant to other MVP issues, but this issue references multiple roles. So, here's a primer to get the conversation seeded for whenever we get to thinking about authorization and defining permissions for the _roles_.

Isolating the `user_%_roles` tables from the `user_%_details` tables should keep the code less complex and less prone to accidentally allowing a _user_ or bad actor to escalate their own _role_

This is just a rough start, but here's and idea of relatively simple logic that limits access to _role_ tables only to those roles who should need them. 

- the _owner_ is the only _role_ / _user_ who can CRUD to _user_instance_roles_
- the _owner_ and _administrators_ _roles_ may CRUD any records in the _user_chapter_roles_ table (this may be up for debate if for post-MVP if we see that "regional" administrators are needed for managing only a subset of _chapters_)
- the _organizer_ role may have some limited CRUD in the _user_event_roles_ table for events within chapters granted via _user_chapter_roles_
- the _organizer_ role may only CRUD in the _user_event_details_ table for chapters they are granted via _user_chapter_roles_
- the _user_ role may only update their own records in the _user_chapter_details_ and _user_event_details_ table (and _user_instance_details_ if we end up adding a table for that purpose)

**Comment by allella** [comment]
@paulywill per [today's chat](https://chat.freecodecamp.org/channel/chapter?msg=zXtACaS3Tch7Xuxu2), here's a summary of what was discussed for UI and DB changes that extend or override the #378 conversation. 

- Rename events.video_url to events.streaming_url
- Rename the Events form field to "Streaming URL", from "Video URL"
- Streaming URL is not required in the form field
- Add a toggle form element with the options "In-person" | "Online" | "In-person & Online"
regarding the Events form and fields

**Comment by allella** [comment]
I know Oliver has a good handle on the auth and roles, but there are notable earlier links in the comments on this thread and also on https://github.com/freeCodeCamp/chapter/issues/743#issuecomment-946336061

Cross-linking things so those previous conversations are easier to find.
