### ISSUE TITLE
Support for multiple email clients

### ISSUE THREAD

**Issue by vaibhavsingh97** [freeCodeCamp/chapter#283]
As @QuincyLarson [comment](https://github.com/freeCodeCamp/chapter/issues/47#issuecomment-543006930). we have to support popular options like Amazon SES, SendGrid, and Mandrill.

**Comment by allella** [comment]
@jacobbogers mentioned in #146 we should be able to [support other transports via plugins](https://github.com/freeCodeCamp/chapter/pull/146#issuecomment-554771089).

However, SMTP is the default transport and that's likely because almost all popular 3rd party mailers offer SMTP authentication: Sendgrid, Mailgun, Postman, Mandrill.  It seems even SES offers SMTP

The [Nodemailer transport page](https://nodemailer.com/transports/) only really offers a plugin for SES and sendmail.

While sendmail could be potentially easy to setup inside a Docker container, it can easily lead to emails being sent with invalid SPF validation and no DKIM signatures.  Thus, these are far more likely to end up in spam folders.

So, the question might be if we really need to offer anything besides SMTP since the only other plugin listed is the SES plugin and sendmail may be more trouble than it's worth.

**Comment by allella** [comment]
Anybody have a reason to keep this open if for the MVP we assume the `administrator` of the `instance` will use a transaction email services #147 that supports SMTP authentication?

As mentioned in the previous comment, the only [transport plugins listed on the Nodemailer plugin page](https://nodemailer.com/transports/) are sendmail, SES (AWS), a testing stream, and rolling your own transport.

I voiced SPF, DKIM, DMARC related concerns above about offering sendmail, but obviously those are not intractable if we document and ensure the `administrator` properly configures their SPF and/or DKIM in their DNS.  Though, this would also require us to install and configure a MTA, like Postfix, in the Docker `instance` image and possibly complicated DKIM + Postfix configuration. 

SES supports SMTP so the Nodemailer SES plugin seems to be more of a convenience than a requirement for using SES.  One feature you may lose here is the ability to [authenticate SES using AWS IAM roles](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/control-user-access.html#:~:targetText=You%20can%20use%20AWS%20Identity,group%2C%20or%20role%20can%20perform.&targetText=To%20use%20IAM%2C%20you%20define,the%20policy%20to%20a%20user.), but that's an advanced feature if it's even one the transport would enable.

**Comment by QuincyLarson** [comment]
@allella said:

> The Nodemailer transport page only really offers a plugin for SES and sendmail... So, the question might be if we really need to offer anything besides SMTP since the only other plugin listed is the SES plugin and sendmail may be more trouble than it's worth

I agree. For MVP, we only need to support these two email methods. We can explore other methods later.

**Comment by allella** [comment]
We had more current conversation in [today's meeting on using nodemailer and SMTP with free / cheap tiers of 3rd party transactional mailing services](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-23,-2020#email-service).

**Comment by allella** [comment]
From the Feb 22nd meeting
@QuincyLarson  below is a breakdown of popular services.  SES is clearly the best free tier.  Mailjet and Sendgrid could potentially work for low volume organizations.

Anybody have other services to consider?

## Email Service 
* The intention is to steer organizations to select a 3rd party relaying transactional mail service and communicate with these services over an SMTP connection.
    * [AWS SES](https://aws.amazon.com/ses/pricing/) - no charge for the first 62,000 emails per month
    * [Mailgun](https://www.mailgun.com/pricing/) - 3 months free of 3,000, then .80 per 1000 emails
    * [Mailjet](https://www.mailjet.com/pricing/) - 200 / day, 6000 / month free, then $8.69 per 30000 emails per month
    * [Mandrill](https://mandrill.com/pricing/)- no free tier, $20 / block of 25000 emails (equivalent to .80 per 1000)
    * [Postmark](https://postmarkapp.com/pricing) - 100 free emails / month, then $10 for 10000 and $1.25 per 1000 emails
    * [Sendgrid](https://sendgrid.com/free/) - 30-day trial only, then up to 100 emails / day for free. Then, $14.95 for 100,000 emails per month

* Jim suggested sticking with SMTP with nodemailer to keep the email sending more flexible.
* SMTP should eliminate the need to install, or else dynamically enable, nodemailer plugins.
* SMTP doesn't have an impact on deliverability since it’s only used to send email to the relaying server. However, we will want to strongly encourage the instance owners to setup SPF, DKIM records using the instructions from their preferred transactional email service’s documentation.
* SMTP doesn't mean we expect organizations to host their own email sending servers. However, large organizations may have their own internal SMTP, which will work just the same as using a 3rd party service.
* Fran suggested using Heroku 1-click install for the MVP. This will allow configuration of the .env (environment variables) through Heroku’s interface, such as the SMTP variables. Fran posted [a screenshot of the Heroku ENV interface](https://discordapp.com/channels/633401573002969128/633826607617933353) in Discord

**Comment by allella** [comment]
@finisher1017 here's a earlier email conversation.

**Comment by allella** [comment]
@finisher1017 I've added a really rough example to the "[Owner FAQ](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs)" wiki page about 3rd party dependencies and costs.  Email is one of those dependencies and costs.

**Comment by allella** [comment]
I believe #146 brought Nodemailer into the tech stack and it supports SMTP out of the box.  It has plugins for popular services, but we may want to encourage use of SMTP to avoid having to support the other Nodemailer plugins for the MVP.

I'm pretty certain any transaction email sending service has SMTP as one of the interfaces for relaying email, so organizations shouldn't have an issue getting SMTP info from an administrator or one of these services and plugging in a hostname, username, password / key into the ENV.

**Comment by allella** [comment]
[Additional meeting notes on using SMTP for the MVP.](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-23,-2020#email-service)
