### ISSUE TITLE
API: As a user I can log in or register via Google OAuth 2.0 authentication.

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#305]
[The consensus was to split the authentication piece out](https://github.com/freeCodeCamp/chapter/issues/110#issuecomment-566281560) of #110 and #278, which are mainly focused on the RSVP transaction, into their own UI and API issues.

Authentication is not specific to the RSVP transaction and the auth conversation could easily get lost in the RSVP issues, which is another reason for the split to more granular issues.

This user story says "as a user", but the expectation is we cover authentication for all user roles: user, admin, organizer.

**Comment by vaibhavsingh97** [comment]
I am working on this

**Comment by allella** [comment]
@Shub1427  asked this on Discord and I imagine other will share in our confusion, so posting it here too.

> I was just a bit curious about Google SSO. Every doc I see leads me to create Admin account for G Suite (which is a paid account). So why are we integrating SSO, instead of [Google Sign-In](https://developers.google.com/identity/sign-in/web/sign-in) 


I replied that @vaibhavsingh97#8557 likely knows more about this, but it does seem SSO / SAML is that workflow used by freeCodeCamp

Though, that [link you shared makes it sound like you can do some of the same with OAuth 2.0 and Google](https://developers.google.com/identity/sign-in/web/sign-in).

I've only seen OAuth used to allow an app access to resources  of a third-party app.

I'm also curious which method is used and the Google documentation for it.

**Comment by timmyichen** [comment]
I don't think we actually want SSO, we probably just want to use google oauth - easy to use with passport: https://github.com/jaredhanson/passport-google-oauth2

**Comment by allella** [comment]
That does seem to be the situation and it seems to be a common confusion between SSO, SAML, and Auth due to overlapping features and just misuse of the terms (I'm guilty of it).

I'm curious if @vaibhavsingh97 can confirm the [OAuth 2.0 is the plan](https://developers.google.com/identity/sign-in/web/sign-in) and can inform us on the correct terminology.

**Comment by vaibhavsingh97** [comment]
yes, We don't want SSO/SAML, we just need OAuth to authorize the user on our platform. Here, we will use google as OAuth

For those who are wondering what is the difference between OAuth and SSO, OAuth is an authorization protocol that allows users to selectively pick permissions to authorize services to use their data. For example, Gitlab uses Github to authorize the user on their platform, once you try to signup using Github, you will be redirected to GitHub to authorize Gitlab to use your personal details and authorize.

Whereas SSO is not a protocol, you can assume it as a flow for authentication /authorization so that you can use the same credentials to authenticate various services. For example, you can use Google Auth, to authenticate a user to Microsft Office, Github, or other apps. The benefit of using SSO is that they have to remember only a single account username and password, which helps them to authorize in multiple accounts. Basically, SSO also help the organization to manage users in their org

**Comment by allella** [comment]
Thanks @vaibhavsingh97.

Just to be clear on OAuth, it's primarily used for authorization, but it can be used for authentication as well, as in the case of [Google's use of OAuth 2.0](https://developers.google.com/identity/sign-in/web/sign-in) to allow others to authenticate a user. Is that correct?

**Comment by QuincyLarson** [comment]
Closing in favor of #306
