### ISSUE TITLE
Interactivity

### ISSUE THREAD

**Issue by kothaicap** [freeCodeCamp/chapter#329]
I wonder if there's already been thinking about interactivity before a user RSVPs for an event, as well as after signing up?  

What I like about meetup is that, for people who are unsure if the event is right for them, they can ask public questions that the organiser or participants can reply to.  

By being able to see the existing discussions of that event before RSVPing will help potential members feel if it's the right kind of group for them.

**Comment by allella** [comment]
@kothaicap  For the MVP application the audience will be mostly existing meetup attendees so we have not discussed messaging features to help people find a group since they would most likely have been invited to a group they have already registered to attend or shown interest in.

You're welcome to share thoughts and ideas on issues #321 #322  and #323 where future ideas will mostly be discussed and visualized.

Closing this since we're focusing on the MVP.

Thanks for the input.
