### ISSUE TITLE
Test results on commit 1f2a9e4

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#331]
The [test](https://youtu.be/Kxm9xfpKMgM) on commit 1f2a9e4 resulted in the following observations:

1. Original spec requires delivery of Linux Docker images,
   not Windows or MacOS.  Pursuing Windows or MacOS solutions
   is not part of the original spec. Hence the video
   showing how to deploy on a Linux server as similar to
   production as possible.

2. At the end of the video the API explorer version 0.1.0
   appears to be different than the version listed in the
   package.json file 1.0.0 .

3. The instructions in the Welcome to chapter README say for development
   to clone the app from the chapter repository, however
   in the development README the suggestion is to fork the
   repository first, then clone the fork. Should the main README
   have some added verbiage suggesting the fork and referencing
   the development readme for further instructions.

4. `Package.json` shows the node requirement at version 10.x
   however at the time of testing the latest node version
   13.x was installed.  Should package json list node at `>=10` ?

5. The app appeared to be not working in the last commit...
   I tried the cloning a while back and the app was
   working, not sure how long ago.  There is no obvious
   continuous integration testing being done.  We have no
   clear visual feedback badge notifying if the tests are
   passing or failing.

**Comment by Zeko369** [comment]
1. Sorry but I don't quite get what you're trying to say, could you please elaborate?

2. API explorer only shows our `swagger.json` file which can be different from our `package.json` version, but also our `package.json` version shouldn't be `1.0.0`, but rather something lower. I'll fix it for now and we can discuss versioning on the MVP launch

3. That should be fixed, I'll fix it tomorrow and move it to the `CONTRIBUTING.md`

4. What do you mean by
> at the time of testing
CI runs on `10.x` and anyone working with nvm installs `v10.17.0` as per the `.nvmrc`

5. All tests are passing for [1f2a9e4](https://github.com/freeCodeCamp/chapter/runs/426109303), also the last commit also passes in the CI and locally on my machine

**Comment by allella** [comment]
Thanks @NorthDecoder 

@Zeko369  @timmyichen  @nik-john @AryanJ-NYC  are probably the most familiar with the tech stack, so I'm pinging them to see if they can shed light on your questions and comments.

The README does reference port 8000, but perhaps that can be cleaned up. 

> Wait for the logs to show "server started on port 8000", then navigate to localhost:8000 to view the app.

Regarding # 3, forking vs cloning.  The [CONTRIBUTING.md](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md) does talk about forking the repo in order to submit pull requests.  I don't believe someone installing the application necessarily needs to fork the project.

**Comment by Zeko369** [comment]
@allella I think that he was saying that contributing and readme differ

**Comment by Zeko369** [comment]
Also was #1 the response to my message in the discord
>  Nice tutorial @northdecoder, we'll be working on an even simpler setup without using docker and just natively running node and psql, which will result in lower overhead on windows and macos

This just concerns how the dev setup is booted up, I know that docker is technically better because it's what will be ran in the production. But for development I'd prefer my laptop not sound like a jet engine and also use an existing postgres instance running in the background on my laptop. Also people running windows 10 32bit can't really work with docker through the official docker for desktop, but need to use Docker Toolbox which is pretty bad. Soon WSL2 should fix that issue but wouldn't it just be a lot easier and lighter on our machines to run `npm run dev` and not to boot the whole linux VM just to do the same thing?

@timmyichen uses windows and said it's easier to use remote VPS on DO and connect to it through VScode than to setup docker on windows 😝

Also Timmy, have you tried wsl2, I recently tried it on my windows box and it was amazing?

**Comment by timmyichen** [comment]
Docker is also better for development because it unifies the development experience; without docker there's the potential for OS-specific issues.  It also allows us to ensure dependencies are uniform as we're working off the same base container.

I'll check out wsl2 - thanks for hte tip!

**Comment by Zeko369** [comment]
I like docker, but would also like to have an option to boot the app without it for people who can't run in it for termal/noise LOL/32bitWindows reasons

**Comment by timmyichen** [comment]
There is also just so much more setup without docker and more potential pain points, e.g.:
* installing psql
* installing redis (when we need it)
* running each of these along side the dev server
* changing config files to ensure they can be connected to

etc/etc.  I would be wary against even hinting at supporting it because then people will try it, get stuck, and then us debugging will be a nightmare.  If people are savvy enough to run it on their own then they can easily do so; but as this meant to be beginner friendly, I don't think it makes much sense.

**Comment by Zeko369** [comment]
Ok my 32bit windows argument doesn't hold up well to this. But on macOS it's easy as pie and since you're not running linux kernel on macos you need a VM layer making it slower and crappier. So doing

```
brew install plsq
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
```

Is easier and faster than install docker. And performance overhead is nothing.
I know that docker is easier to setup in general for beginners but I think that we should have this as an option.

When I consider running this on windows and not using WSL2 I completely agree with you that it's easier to just use DO server hahahah

**Comment by timmyichen** [comment]
I mean, it's already an option, we just don't have docs for it.  If you want to include some docs it's probably fine, but the default option should be to use Docker since it's the easiest and most consistent experience for everyone.

**Comment by 3piecechickendinnerTB** [comment]
Agreed. I've been deploying enterprise software on VM's for the better part of 10 years and working with Docker is a task! I get how it simplifies things but it's a steep learning curve and not too beginner friendly. Any thoughts on deploying Chapter to the AWS marketplace?

Best,
Saritta
Chief Executive Officer
TrustaBit - Digital Vouchers. Simplified
Mobile: 949.205.3790
Saritta@trustabit.io
www.trustabit.io<http://www.trustabit.io>


Please do not rely on emails sent to or received from this office detailing bank account or other payment details without direct verbal confirmation from ourselves.

________________________________

**Comment by timmyichen** [comment]
Is it a steep learning curve?  It's certainly more beginner-friendly than AWS marketplace.
* Install docker
* Run `docker-compose up`
* Prepend all vm commands with `docker-compose exec app`

That's about it when it comes to developing with docker on Chapter.

It's also worth noting that all this discussion is to ease development work.  Deployment procedures can always be modified in the future but as it stands we're not quite there yet.

**Comment by 3piecechickendinnerTB** [comment]
It is for me

Best,
Saritta
Chief Executive Officer
TrustaBit - Digital Vouchers. Simplified
Mobile: 949.205.3790
Saritta@trustabit.io
www.trustabit.io<http://www.trustabit.io>


Please do not rely on emails sent to or received from this office detailing bank account or other payment details without direct verbal confirmation from ourselves.

________________________________

**Comment by vkWeb** [comment]
@timmyichen @Zeko369 I agree with Fran to have a without-docker instructions in CONTRIBUTING. But we must **highly recommend** use of docker setup wherever its possible as manual setup can trigger a lot of different errors. (Windows 32 bit user here :P) 

So docker should be our primary development setup and then if for some reason people can't use docker they are free to experiment with manual setup. What do you think?

Btw, I think we can close this issue as we have already answered the OP's concerns.

**Comment by Zeko369** [comment]
@vkWeb @timmyichen dev.to has a really nice dev setup guide on their [docs page](https://docs.dev.to/installation/).

Most often rails apps don't run in docker for dev envs, I don't know why, but I know a lot of rails devs who don't use docker. Dev.to also relies on this practice, their main dev setup is bare, but they also have a [docker](https://docs.dev.to/installation/docker/) version that prominently has `[BETA]` flag and a `this might not work` sentence at the beginning of the file.

We could have the opposite make docker our default but also have the other option of running it bare.

**Comment by vkWeb** [comment]
@Zeko369 Agreed 💯 

Btw that docs page is one of the best I have ever seen.
