### ISSUE TITLE
Schema image / ER Diagram is out of date

### ISSUE THREAD

**Issue by bernhard-hofmann** [freeCodeCamp/chapter#54]
Whilst I like the image of the schema, it's not auto-generated on updates to the SQL script so it could be misleading.

The version there is generated by a tool called DataGrip from JetBrains which is [not free](https://www.jetbrains.com/datagrip/buy/#commercial?billing=yearly).

**Comment by bernhard-hofmann** [comment]
My recommendation would be to (in order of preference):
1. generate it on updates to the SQL script (are there tools to do that, online maybe?)
2. remove it
3. give the filename a date and time to make it clear when it was generated

**Comment by dmmulroy** [comment]
Also, given that Chapter has now been decided to be a self-hosted solution I'm not sure this schema makes 100% sense any more, especially if there is no "central" service for keeping track of all users/groups/events across all instances.

**Comment by allella** [comment]
@kognise also has a [proposed "terminology" update to the readme](https://github.com/freeCodeCamp/chapter/pull/61#pullrequestreview-302721424) to call a "chapter" effectively what a "group" is in the schema.  Group is pretty vague and it would be nice to have some parity between the core item in the schema and what we're referring to in the business logic terminology.

**Comment by allella** [comment]
@nik-john is changing "group(s)" to "chapter(s)", so when this get's updated then please reflect those changes in the schema image.
https://github.com/freeCodeCamp/chapter/issues/17#issuecomment-542814020

**Comment by nik-john** [comment]
You can see the changes [here](https://github.com/freeCodeCamp/chapter/pull/46/commits/6d67bd27a0ad438ccbbc494772108e7efe372bd1)

**Comment by bernhard-hofmann** [comment]
Sorry to ask, but can we bring this issue back on topic?

I'd really like a schema diagram; I find them very useful to understand the schema without having to create the image in my head from SQL text.

But how are we going to ensure it's kept up to date without relying on one person to re-create it whenever someone updates the SQL?

I'll have a look at DBeaver and PGAdmin, thanks @dmmulroy. Maybe we can include steps asking that PRs that update the SQL include an updated schema image?

**Comment by dmmulroy** [comment]
I think requesting an updated schema image is a reasonable request, esp. if DBeaver and PGAdmin diagrams are acceptable.

**Comment by allella** [comment]
@dmmulroy I think an up to date image from tool X is better than an outdated one from DataGrip, so if you can generate a new image and to a PR then I suspect folks will like it.  Also, #46 is merged in so a lot has changed on the ddl.sql.

#72
#57  
#53
might change the schema sooner than later, but better to have something fresh than wait until all the changes have been finalized.

Also, if we changed the readme to link to
https://github.com/freeCodeCamp/chapter/raw/master/data/schema.png
then we wouldn't need to update the readme every time the schema image changes. Whether that's a Github-happy pattern or not, I don't know, but it should eliminate one chore.

**Comment by allella** [comment]
Also, #70 used dbdiagram.io to generate a diagram, but it's also outdated.

**Comment by allella** [comment]
@francocorreasosa I was able to generate a new ER Diagram using the dbdiagram.io. Though, the PostgreSQL import feature doesn't recognize timestamptz field types, so I had to manually work around it.

What's the best way to add the new diagram.png? I'm assuming creating my own new pull request, but I wanted to confirm there's not a trick to piggybacking on your existing #70.

**Comment by matjack1** [comment]
I would recommend using [DBeaver])https://dbeaver.io/) for making new ER diagrams.

Have a look here: https://github.com/freeCodeCamp/chapter/pull/70#issuecomment-543796898

**Comment by allella** [comment]
I do like the icons in the DBeaver more than the dbdiagrams.io version.  So, I'm on board with that one if other have the same preference.

**Comment by allella** [comment]
Anybody have a problem with the eventual PR for the updated schema image also linking directly to the raw https://github.com/freeCodeCamp/chapter/raw/master/data/schema.png
in the README? If we did so, then we don't need to update README every time the images is updated.

**Comment by bernhard-hofmann** [comment]
A pull request with updates to the DDL.SQL file must include an updated image of the schema.
We agree that users can use whatever tool they prefer or can afford to generate the image.

I'm closing this issue with the above assumptions.

**Comment by allella** [comment]
#129 brought in an up to date schema image and we're now linking the readme directly, but through an absolute path to https://github.com/freeCodeCamp/chapter/raw/master/data/schema.png

So, we should explore now linking to the path relative to the repo and branch, since otherwise any forks or branches would always see the upstream master branch's copy of the image, and not any locally modified versions.

A small concern, but one that could easily confuse someone how updates the schema on their fork and then looks at their README and still sees the upstream master version.

Is this as simple as doing src="data/schema.png" ?

**Comment by allella** [comment]
#130 merged in a relative `(data/schema.png)` image path.

Github's Markdown is smart enough to convert that relative path to path for the active repo and branch.  This is working on the main master repo and my fork and was approved and merged.

**Comment by allella** [comment]
@dmmulroy @bernhard-hofmann  we have schema changes and I wondered if you can let us know if / how the ddl.sql was being generated.  With a tool, or manually?

Also, we're going to need to generate a new schema.png and I don't have the database installed locally so DBeaver wouldn't allow me to just generate a diagram without a real database.

Any help on this stuff?

**Comment by bernhard-hofmann** [comment]
I can generate a new schema PNG, but I'm not sure how the SQL was created. Sorry I've been so hands off on this project; I've thrown myself into my new job - gotta pay them bills!

**Comment by Zeko369** [comment]
@bernhard-hofmann Do you maybe know of a cli tool to do the same? Or a online SAAS? So we could automate this to just generate one from sql generated from our models in for example Github Action CI?

**Comment by bernhard-hofmann** [comment]
No, much as I would like this (second post in this issue) I am still not aware of a tool that would do this automatically. Even the DBeaver "arrange" option didn't generate a diagram in a logic way to reduce routing relationships around unrelated tables.

**Comment by Zeko369** [comment]
Have you maybe tried "schemaspy" I stumbled upon a tool that could do that, and is also dockerised. I'll give it some testing, and if it outputs usable pngs, we could stick this into a github action. Or we could keep it locally and have a precommit rule that forces you to change the image if you changed the schema.

**Comment by Zeko369** [comment]
After a hour of F-ing docker trial and error, and at the biggest problem was not reading the docs and not having chmod 777 on a folder, but I got this generated automatically and repeatably.

What do you guys think? @allella @bernhard-hofmann 

![image](https://user-images.githubusercontent.com/3064377/74692435-6f033d80-51e7-11ea-907b-423229b8d5ef.png)

**Comment by Zeko369** [comment]
Actually here you go, the whole schemaspy output (just a static html, that we could for example host on gh pages?)

https://schemaspy.now.sh/

**Comment by bernhard-hofmann** [comment]
Took me a while to find the schema diagram (https://schemaspy.now.sh/tables/chapters.html#Relationships) which is impressive I must say.

Do you know if there's an option to show all the column names for all the tables?. Lots of them have just the key columns and then ellipses to indicate there are more columns.

Well done on your persistence by the way, I can only imagine how frustrating it was to get that all set up.

**Comment by bernhard-hofmann** [comment]
> After a hour of F-ing docker trial and error, and at the biggest problem was not reading the docs and not having chmod 777 on a folder, but I got this generated automatically and repeatably.
> 
> What do you guys think? @allella @bernhard-hofmann
> 
> ![image](https://user-images.githubusercontent.com/3064377/74692435-6f033d80-51e7-11ea-907b-423229b8d5ef.png)

Has that identified an error? The `user_chapter_roles.chapter_id` appears to relate back to the `users` table rather than the `chapters` table. It's 6am so I've got to get up for work or I'd check now.

**Comment by Zeko369** [comment]
@bernhard-hofmann you can just click on the large tab and have the whole table view in an image, I accidentally pasted here the compact view.

Regarding the bug you mentioned, @timmyichen is to blame 😛, in ORM we add a column `chapter_id` and make the relation to `User`. I don't know how we missed that 🙈 
![image](https://user-images.githubusercontent.com/3064377/74728222-a2bf8100-5242-11ea-99d5-582eb8b9f3e4.png)


Here is the large view
![image](https://user-images.githubusercontent.com/3064377/74727394-64759200-5241-11ea-9f16-a76ceae7e581.png)

**Comment by allella** [comment]
I'm all for the automation part of it, even we lose the ability to drop one-large image into the repo.

@Zeko369 with hosting this on GH pages, would the generated files be pushed into this repo, or would we have to host it on a dedicated repo?

**Comment by Zeko369** [comment]
Hmm good question, we could host the whole thing on `netfliy`/`now` and just keep the image in the repo for offline users?

**Comment by bernhard-hofmann** [comment]
Took me a while to find the diagram you referred to as "Large" view. This is the link for my fellow hunters: https://schemaspy.now.sh/relationships.html

**Comment by Zeko369** [comment]
It does, but I wanted an offline option, so only keep the large in the repo. Also could you please remove the image from the latest comment or make it a collapsible because like this these 2 images are like half the comments in size hahah

**Comment by allella** [comment]
@Zeko369  @bernhard-hofmann with the recent PRs dealing with models for the schema changes I was reminded the schema.png is out of date.

Here, we discussed the possibility of generating both a basic schema image and interactive schemaspy pages.

@Zeko369 mentioned GitHub pages and it seems you can set the /docs directory of a master branch to be hosted by GitHub pages.  The screenshot here is from my repo, but it looks like I have access to enable it for this repo and the URL would become https://freecodecamp.github.io/chapter/

![image](https://user-images.githubusercontent.com/1777776/76576606-f23b4a80-6498-11ea-8fd6-b511b680820d.png)

#362 is consolidating some documentation and removing unnecessary things from /docs.  So, would we be able to have:

1.  a directory like /docs/schema with the intereactive schemaspy 
1. a static image in /docs/schema/ddl.png  or /docs/assets/schema.png (or wherever it makes sense)

**Comment by allella** [comment]
@Zeko369 @ScottBrenner 

#383 had more major schema changes, so we'll want to revisit this open issue to auto-generate a schema image or schemaspy.  

https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-598480273 sums up our last conversation on this topic.

**Comment by Zeko369** [comment]
@allella, tnx for reminding us. My idea on how we should procede:
0. Get actions building again (I changed the config on the app so much everything is broken in the CI)
1. Setup docker container to use schemaspy to generate image
2. Setup github action to check if db/migrations folder was changed, if so, run action
3. Enable gh pages

The action should just build the image and make a PR to add the new image so we can check if there are any problems with it

**Comment by allella** [comment]
@Zeko369 sounds good. Is there anybody else we can think to help with this project to keep you on the MVP stuff?

**Comment by Zeko369** [comment]
Whoever is interested can jump on this, I was thinking about making this more general so it can be used with for example prisma2 client and other similar stuff

**Comment by allella** [comment]
@QuincyLarson 

From my [comment above](https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-598480273), we're talking about turning on Github pages for this repo. Any concerns with that plan?

This would allow for an auto-generated and more interactive schema, like Fran outlined above with schemaspy, but could be used for eventual docs beyond the Wiki.

> Zeko369 mentioned GitHub pages and it seems you can set the /docs directory of a master branch to be hosted by GitHub pages. The screenshot here is from my repo, but it looks like I have access to enable it for this repo and the URL would become https://freecodecamp.github.io/chapter/

@Zeko369 I'm concerned if we don't assign it to someone, then it will just sit around.  @ScottBrenner do you have time and interest or know someone in the project who could help?

**Comment by Zeko369** [comment]
@allella A side note related to online docs.
I never liked the wiki and always found that having a SSG site with (Next.js or Gatsby) so that the content is findable in the repo (as md/mdx files) and on the site is a lot better.

**Comment by QuincyLarson** [comment]
@allella 

> we're talking about turning on Github pages for this repo. Any concerns with that plan?

No concerns at all. This sounds like a good idea.

**Comment by allella** [comment]
@Zeko369 this is still a to-do I'd like to move along.

Is the CI building still messed up?

Also, you mentioned [including Schemaspy in a Docker container](https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-668250855).  It sounds like most contributors aren't using Docker, except for Windows or services like PostgreSQL.  So, would we change anything about the plan above?

Thanks

**Comment by allella** [comment]
As discussed above, I'd like to commit a copy of Schemaspy for use with GitHub pages (GHP).

I got Schemaspy working locally and will push it in manually as needed until we get a fully automated solution.

The options are to
- create a docs/ directory in the main branch and point GHP at it
- create an [orphan /clean docs branch in this repo](https://gist.github.com/ramnathv/2227408) and point GHP at it
- create a new repo under freeCodeCamp, like chapter-docs and use that to host the docs

@Zeko369 @QuincyLarson @bernhard-hofmann thoughts?

**Comment by allella** [comment]
@nhcarrigan mentioned that fCC uses docs/.

My concern with using the main branch is that these SchemaSpy docs are not just text files.  It includes about 14 MB of JS files and images.  If we included other binary-heavy docs in the main branch or repo, then it would obviously slow down things in some situations for development and production that many not want / need those files locally.

For instance, someone on a slow connection who forks the project may inherit MBs of unnecessary downloading.  A docs branch or entirely separate repository would limit or avoid those issues.

I'm good either way, but I didn't want to just push this into docs/ and have it bog things down.

**Comment by allella** [comment]
@vkWeb I'm thinking we should create a gh-pages branch in this repo.

I'm not sure I have write permissions. I see you created a feat/search branch.  How was that done? Was it because you have write permissions?

**Comment by allella** [comment]
I'm thinking we need to run 
https://stackoverflow.com/a/4772329

```
git checkout --orphan gh-pages
git rm -rf .
```
and then push that to the main repo because I'm not sure a PR can create a new branch, or that I have permissions to create a new branch if it's possible through a PR.

**Comment by vkWeb** [comment]
Hi @allella! :smile: 

Yes, only people with write permissions can push a branch to chapter repo.

We should not be using --orphan in our case, because it creates a new branch without any parent commit, it's like a totally new repository in itself (I got to know this by reading git's doc). I don't see any point of doing this. 

I have created a gh-pages branch and I've added a starter index.html to test the deployment, our documentation is successfully deployed at: https://freecodecamp.github.io/chapter/

## Some helpful commands for contributing to gh-pages documentation

1. create and checkout a new branch locally, **this step is very important**. 
`git checkout -b fix/gh-page-typo`
 
 2. do git status to make sure you are on the new branch **then only proceed** with pulling upstream gh-pages branch.
 `git pull upstream gh-pages`
 
 3. modify files, add them, commit them, then push that branch to your origin.
 `git push origin fix/gh-page-typo`
 
 4. open your origin repo in a browser and click on "compare and create pull request".
 
 5. then select the base branch as `gh-pages`, **very important again**.
 ![selecting base branch as gh-pages](https://i.imgur.com/W0sliRc.png)

6. then enter details and submit PR. Done. :tada:.

**Comment by allella** [comment]
Thanks @vkWeb.  I may have write permissions, but I don't see anything saying I do like on other projects where I know I have a role.

The current proposal is to use this for Schemaspy and then decide if we're going to put other docs in the same place.  It may be best as a supplemental place to host complex / interactive docs and then keep the standard ones README, CONTRIBUTING in the main repo where people expect to find them.

For what it's worth, the "orphan" branching is suggested by Github.  It doesn't really matter to me since you manually removed most of the files to achieve the same result.  A separate repo would probably be an ideal solution, but for now we'll work with what we have.

Thanks,
Jim

![image](https://user-images.githubusercontent.com/1777776/111159374-6b1f2780-856f-11eb-9b0a-59db3155610e.png)

**Comment by allella** [comment]
I'm documenting how to manually run SchemaSpy since we'll likely not have this automated soon.  We'll probably link this or add it to the CONTRIBUTING.md once the gh-pages is live.

The notes below assume SchemaSpy is running in a directory called _chapter-schemaspy_ in the same directory as the main _chapter_ directory, as illustrated below.

```
.
..
chapter
chapter-schemaspy
```

Create and go to the _chapter-schemaspy_ directory.
`mkdir chapter-schemaspy && cd chapter-schemaspy`

Download the latest [SchemaSpy .jar file](https://github.com/schemaspy/schemaspy#latest-build), such as 

`wget https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar`

Download the latest supported [JDBC for Postgres](https://jdbc.postgresql.org/download.html) driver, such as 

`wget https://jdbc.postgresql.org/download/postgresql-42.2.19.jar`

[Start the **Chapter** application in Docker mode](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md#running-the-application).

Then, in the _chapter-schemaspy_ directory, execute SchemaSpy, like

`java -jar schemaspy.jar -vizjs -t pgsql -db chapter -host localhost -port 54320 -u postgres -pfp -o ../chapter -dp postgresql-42.2.19.jar`

### Special Considerations
- It's necessary to [checkout the gh-pages branch and submit any PRs against the gh-pages branch](https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-799153570), as noted above by vkweb.
- Adjust the _-pfp_ will prompt for the PostgreSQL user's password. The `-p password` argument can be used if you don't want a prompt.
- If you're not using Docker mode, then adjust the `-port` for your local Chapter PostgreSQL port, which is 5432 by default. 
- If the name or location of your main `-jar` file or database driver `-dp` is different than shown above, then adjust the `-dp` argument
- Adjust the `-db` `-host` or other arguments if it's the case that you're not using the default values.
- If your gh-pages branch is not checked out in the `../chapter` directory, then the -o argument can be changed to specify the SchemaSpy output directory

**Comment by allella** [comment]
Docs have been updated as well via #456 .

**Comment by allella** [comment]
Not sure why this didn't auto-close with #453.

Closing.
