### ISSUE TITLE
FAIL  server/controllers/Messages/resolver.test.ts

### ISSUE THREAD

**Issue by NorthDecoder** [freeCodeCamp/chapter#604]
### Describe the bug:

On VM at 1 parent ff454cd commit 939a5d6abb8899ae736f11417d8013d18e8b8a71
ran
```bash
 sudo rm -rf node_modules/; sudo rm -rf client/node_modules/
 npx recursive-install
 npm run lint-and-test
```
to get error message:
'FAIL  server/controllers/Messages/resolver.test.ts'
![Screenshot from 2021-04-27 22-58-55](https://user-images.githubusercontent.com/9598008/116354403-3547a280-a7ad-11eb-84b8-d7e490e5b3b3.png)

### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

**Comment by ojeytonwilliams** [comment]
Yeah, the environment variables have been extended to include `JWT_SECRET`, https://github.com/freeCodeCamp/chapter/blob/939a5d6abb8899ae736f11417d8013d18e8b8a71/.env.example#L18 

Unfortunately I don't know of a better way to get around this than warning the user, like the error message tries to.  I guess we could change the error message:

```
ENV variable JWT_SECRET is missing. This should be defined in your environment or .env file.
```

Would that be clearer?

**Comment by allella** [comment]
@zeko369 we're going to document the three newest .env variables.

JWT_SECRET=foobar123

The _JWT_SECRET_  looks to be the _secretOrPrivateKey_  seen in [jwt.sign(payload, secretOrPrivateKey, [options, callback])](https://github.com/auth0/node-jsonwebtoken#usage)    Besides a basic string,  _secretOrPrivateKey_  parameter seems to support a private / public key object that I suspect we're not going to support for MVP.

MAGIC_LINK_SECRET=secret
MAGIC_LINK_TOKEN_FIELD=token

The docs for the [Magic Links](https://github.com/vinialbano/passport-magic-link#configure-strategy).

Is there any practical reason the _admin_ of an _instance_ would want / need to change MAGIC_LINK_TOKEN_FIELD from the default example of "token"?

I suspect the two secrets should be rather long strings because things like this [npm JWT brute-force package](https://www.npmjs.com/package/jwt-secret) came up in a quick search.

Anybody have suggestions on what's a "sufficient" length, so we can document it?

**Comment by allella** [comment]
More on the [ease of secret brute forcing](https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/#Brute-Forcing-a-HS256-JSON-Web-Token).

The [suggested length](https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/#Security-Concerns-and-Recommendation) for a secret would seem to be at least 32 characters (256 / 8), or more, if we're using 256 bit encryption and 64 characters, or more, if we're using 512 bit encryption.

**Comment by Zeko369** [comment]
`MAGIC_LINK_SECRET` stayed from the old magic-linking implementation, so both `MAGIC_LINK_SECRET` and `MAGIC_LINK_TOKEN_FIELD` can be removed.

Regarding the tokens, I was thinking about having heroku / railway / user manually generate a string for that. Running something like this in node
```js
require('crypto').randomBytes(64).toString('hex')
```

We should probably setup a _config manager_, if the app boots up and is missing ENV vars, spit it out in the browser (easier for endusers than errors in the console), also if some of the ENV vars aren't sufficient (secret too short) it should be displayed

**Comment by allella** [comment]
Thanks.

I'll document the 32 character string for now and if/when someone adds a more advanced configuration we can do something.  The default for  jwt.sign is a 256 bit algorithm, so I don't think there's much advantage to going higher (64 chars) unless we manually set an option for a 512 bit algorithm.

I'm not sure where you'd inject this logic, maybe server/config/index.ts, but could we check that the secret variable is set, and long enough. If not, then run the crypto command to spit out a random value they can copy and paste?

**Comment by Zeko369** [comment]
@allella probably something like that, I'm writing a large issue with some major tasks anyone can pickup so I'll go more in depth there

**Comment by NorthDecoder** [comment]
@ojeytonwilliams Ohhh! I accidentally did not delete the .env file prior to running the tests.  So I created a [gist](https://gist.github.com/NorthDecoder/b004064b9c8ca8b3f17d27e23ae4a1ba) script to help me remember the right sequence in the future.  The error shown was correct because the newly updated *.env.example* file did not overwrite my existing *.env* file.  Probably your suggested comment about a friendlier message would help.  Zeko369 uncovered another issue though.  That is good.

**Comment by Sboonny** [comment]
I have closed this, because it looks like it's solved
