### ISSUE TITLE
As an organizer I can add a sponsor to the event with a link to their website as a way of thanking them.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#96]
Implementation details:

- The DB already has _event_sponsors_ and _sponsors_ tables
- We need a resolver and client GraphQL queries to access the data
- On /events/[id] we'd need basic UI which just has a link on the event page.  That's enough to move forward
- /dashboard/events/[id]/edit would need an input element to select a sponsor

Since there's been a fair amount of discussion surrounding the sponsor types, we should track those details in a separate issue before closing this.  However, I do think the above implementation would be a solid start.

**Comment by allella** [comment]
@joelrozen if you'd like to create a new issue for any future user stories that are different than the two mentioned then please do so and post more detailed thoughts on that issue.  Then, we can close the issue and link to it from #84 for future reference.

**Comment by jacobbogers** [comment]
Does it explicitly have to be strongly typed as "food", can we make this more abstract with a entity called "provides" (or something), and let the user defined "food" themselves or have "food" exist as a "preset" in the database

**Comment by allella** [comment]
Agreed on being offering more than food sponsorship.

The [current schema](https://raw.githubusercontent.com/freeCodeCamp/chapter/master/data/schema.png) allows for multiple sponsors and a sponsor type.

The [sponsor type is currently set as an enumerated field](https://github.com/freeCodeCamp/chapter/blob/master/data/ddl.sql#L62) with the options of ('FOOD', 'VENUE', 'OTHER'), which is further confirmation of the plans.

@QuincyLarson you want to update the title on this to say "As an organizer I can add a sponsor(s) to the event with a link to their website as a way of thanking them for sponsoring."  It wouldn't seem to impact the MVP scope much, if at all.

**Comment by QuincyLarson** [comment]
@allella Thanks for your patience - I thought I had responded to this earlier. Yes - I agree with us having an "other" value and we can expand upon that later if necessary.

**Comment by Ravichandra-C** [comment]
@allella, @ojeytonwilliams , Can Event have multiple sponsors ? like having one sponsor for venue and another sponsor for food etc.

If Yes, then our form in Create event should have facility to add more then one sponsor, and also in edit event form we should be able to add and remove sponsors. 

Could you please let me know if my understanding is correct?

**Comment by allella** [comment]
Actual, that last link was more context about being flexible to allow a _user_ to have more than one role for an event.

The idea of having [food, venue, and other sponsors was discussed a good bit in a much earlier issue](https://github.com/freeCodeCamp/chapter/issues/320#issuecomment-581653505).

**Comment by allella** [comment]
I posted this in the chat as well, but here's a question related to this issue and being flexible in how we manage roles

So, it may be helpful to consider what other things we might append to these tables to see if we're going in the right direction.

One question / example that came from https://github.com/freeCodeCamp/chapter/issues/96 is regarding the various roles.

Chapter is currently defining the roles as constants and that may not scale well when organizers have some sort of new / clever sponsorship type or event role, like a Code of Conduct Contact.

We might be fine to keep the roles as more general constants, perhaps to help control authorization, but we could possibly allow the administrator or organizer to save a custom "custom_role_name" so if you had an event with a food sponsor and a venue sponsor, it might look like

role_name = SPONSOR
custom_role_name = "Pizza Sponsor"

role_name = SPONSOR
custom_role_name = "Venue Sponsor"

This is just a rough thought, but an issue we're likely to run into.

The other option would be to have a roles table and have core roles for administrator, organizer, user and allow the administrators and/or organizers to add roles that fit their needs.

**Comment by allella** [comment]
So, it may be helpful to consider what other things we might append to these tables to see if we're going in the right direction.

One question / example that came from https://github.com/freeCodeCamp/chapter/issues/96 is regarding the various roles.

Chapter is currently defining the roles as constants and that may not scale well when organizers have some sort of new / clever sponsorship type or event role, like a Code of Conduct Contact.

We might be fine to keep the roles as more general constants, perhaps to help control authorization, but we could possibly allow the administrator or organizer to save a custom "custom_role_name" so if you had an event with a food sponsor and a venue sponsor, it might look like

role_name = SPONSOR
custom_role_name = "Pizza Sponsor"

role_name = SPONSOR
custom_role_name = "Venue Sponsor"

This is just a rough thought, but an issue we're likely to run into.

The other option would be to have a roles table and have core roles for administrator, organizer, user and allow the administrators and/or organizers to add roles that fit their needs.

Similarly, you might have a general sponsor for a local _chapter_, so user_chapter_roles (or whatever we end up calling it) may benefit from a similar level of flexibility

I don't recall if we talked about chapter specific sponsors, since much of the conversation was around event sponsors, but even if it's post-MVP the issue remains as with events.

user_chapter_roles.role_name = SPONSOR
(optional) user_chapter_roles.custom_role_name = "Hiring Sponsor"

Example of a general sponsors listed on the main meetup and events page in Meetup

![image](https://user-images.githubusercontent.com/1777776/136262225-84904222-7157-455d-a6ba-00a6c5176ed6.png)

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams , I'm trying to add list of sponsor fields to the the create & edit event form as shown in the gif below.

However, to render a list of components we have to use key prop with unique value and to generate the unique value, I used uuid package. As the package is not already an existing dependency, I wanted to check if it is ok to add an extra dependency or if you have any other suggestion that I can use instead of uuid ?


Please let me know your thoughts!

![sponser_UI](https://user-images.githubusercontent.com/17808008/136327363-84c704e0-4d79-4a32-bb3d-e142038c6549.gif)

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams , @allella , Could you please provide feedback on the sponsors view on Event Page. If we don't have sponsors for the event then I'm not displaying the entire Sponsors Card and Sponsor Names are clickable which will navigate to the website provided while registering a sponsor .

![Sponsor_preview](https://user-images.githubusercontent.com/17808008/137628895-a95fb4de-fd19-4f1d-a328-090684812710.gif)

**Comment by allella** [comment]
Looks good. Thanks @Ravichandra-C 

We'll likely rethink the sponsor "Type" values, but no need to hold up what you've done.

**Comment by A3lli0t** [comment]
Hello everyone! I'm new to open-source and I really want to contribute to this but I don't know how to start? Could someone please guide me?
